### PR TITLE
Import uuid.v4 member

### PR DESCRIPTION
**Pull request by ryanve**
Another attempt at https://github.com/airbnb/enzyme/issues/1020

### CODE REVIEW

**Comment by ryanve** [comment]
This works :)

**Comment by ljharb** [comment]
This doesn't achieve the desired effect, which is a smaller bundle size. Relying on treeshaking doesn't count :-)

**Comment by ryanve** [comment]
Ha of course : ) Our concern was it just working at all because this is a `devDependency` for us so size was not critical.

**Comment by ryanve** [comment]
Thanks for the help debugging @ljharb : )

**Comment by ryanve** [comment]
We ended up now using `enzyme@2.9.1` and `npm install uuid@^3.1 --save-dev` in the depending projects to fix this for now and posted about the issue in the [uuid project](https://github.com/kelektiv/node-uuid/issues/210).

**Pull request merged**
